# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/server/chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/server/chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15src/server/chat.proto\"\x1c\n\x08\x43hatUser\x12\x10\n\x08username\x18\x01 \x01(\t\"5\n\x11\x43hatUserConnected\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t20\n\x04\x43hat\x12(\n\x07\x63onnect\x12\t.ChatUser\x1a\x12.ChatUserConnectedb\x06proto3'
)




_CHATUSER = _descriptor.Descriptor(
  name='ChatUser',
  full_name='ChatUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='ChatUser.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=53,
)


_CHATUSERCONNECTED = _descriptor.Descriptor(
  name='ChatUserConnected',
  full_name='ChatUserConnected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='ChatUserConnected.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='ChatUserConnected.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ChatUser'] = _CHATUSER
DESCRIPTOR.message_types_by_name['ChatUserConnected'] = _CHATUSERCONNECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatUser = _reflection.GeneratedProtocolMessageType('ChatUser', (_message.Message,), {
  'DESCRIPTOR' : _CHATUSER,
  '__module__' : 'src.server.chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatUser)
  })
_sym_db.RegisterMessage(ChatUser)

ChatUserConnected = _reflection.GeneratedProtocolMessageType('ChatUserConnected', (_message.Message,), {
  'DESCRIPTOR' : _CHATUSERCONNECTED,
  '__module__' : 'src.server.chat_pb2'
  # @@protoc_insertion_point(class_scope:ChatUserConnected)
  })
_sym_db.RegisterMessage(ChatUserConnected)



_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=158,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='Chat.connect',
    index=0,
    containing_service=None,
    input_type=_CHATUSER,
    output_type=_CHATUSERCONNECTED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
